### ISSUE TITLE
Help converting config.gateway.json to a script to use with UDM Pro

### ISSUE THREAD

**Issue by Kopernikus1979** [unifi-utilities/unifios-utilities#154]
Hi,

At the moment I have an USG3 + CloudKeyGen2+ and I will migrate to an UDM Pro and use the udm-utilities as a replacement for my config.gateway.json below is my existing config, can someone help me on the way to make this working with my new udm pro? In the config I have 1. Static host mapping for my controller 2. MDNS for Trusted/IoT VLAN 3. NAT forward/DNS masquerade for my 2 RaspPi running Pi-Hole for devices (most Google speakers etc) who try to bypass my PiHole.

Thx!

```
{
  "system": {
    "static-host-mapping": {
      "host-name": {
        "mydomain.extension": {
          "alias": [
            "unifi"
          ],
          "inet": [
            "10.10.50.10"
          ]
        }
      }
    }
  },
  "service": {
    "mdns": {
      "repeater": {
        "interface": [
          "eth1.20",
          "eth1.10"
        ]
      }
    },
    "nat": {
      "rule": {
        "10": {
          "description": "Redirect Trusted VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.10",
          "inside-address": {
            "address": "10.10.10.5-10.10.10.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.10.5-10.10.10.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
		"20": {
          "description": "Redirect IoT VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.20",
          "inside-address": {
            "address": "10.10.20.5-10.10.20.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.20.5-10.10.20.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
		"30": {
          "description": "Redirect Guests VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.30",
          "inside-address": {
            "address": "10.10.30.5-10.10.30.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.30.5-10.10.30.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
        "6010": {
          "description": "MASQ Trusted VLAN DNS requests",
          "destination": {
            "address": "10.10.10.5-10.10.10.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.10",
          "protocol": "tcp_udp",
          "type": "masquerade"
        },
        "6020": {
          "description": "MASQ IoT VLAN DNS requests",
          "destination": {
            "address": "10.10.20.5-10.10.20.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.20",
          "protocol": "tcp_udp",
          "type": "masquerade"
		},
        "6030": {
          "description": "MASQ Guests VLAN DNS requests",
          "destination": {
            "address": "10.10.30.5-10.10.30.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.30",
          "protocol": "tcp_udp",
          "type": "masquerade"  
		}
      }
    }
  }
}
```

**Comment by renedis** [comment]
**1. [Static host mapping](https://www.reddit.com/r/Ubiquiti/comments/k7tdri/udmpro_static_host_mapping/):**
Install boostchicken's on-boot script. See https://github.com/boostchicken/udm-utilities/blob/master/on-boot-script/README.md

Create the following file

File: /mnt/data/on_boot.d/10SetMyHosts.sh

#!/bin/sh

# create my custom dnsmasq file
cat > /run/dnsmasq.conf.d/mine.conf <<EOF
host-record=udmp,gateway,192.168.1.1
host-record=host111,192.168.1.99
EOF

# force restart of dnsmasq
pkill dnsmasq


This will work across reboots & firmware upgrades (but not factory resets).
I threw in the udmp & gateway line to show an example of multiple hostnames mapping to the same ip.
To run the script without rebooting:

sh /mnt/data/on_boot.d/10SetMyHosts.sh
I recommend that you keep a copy of the script somewhere off the UDMP in case you have to do a factory reset one day.


**2. [MDNS](https://hub.docker.com/r/scyto/multicast-relay)**

3. [DNS masquerade](https://github.com/boostchicken/udm-utilities/blob/master/dns-common/on_boot.d/10-dns.sh)
# set this to the interface(s) on which you want DNS TCP/UDP port 53 traffic
# re-routed through the DNS container. separate interfaces with spaces.
# e.g. "br0" or "br0 br1" etc.
FORCED_INTFC=""


Dit you even read the instructions? This is all available for a long time.

**Comment by Kopernikus1979** [comment]
> 
> 
> **1. [Static host mapping](https://www.reddit.com/r/Ubiquiti/comments/k7tdri/udmpro_static_host_mapping/):**
> 
> Create the following file
> 
> File: /mnt/data/on_boot.d/10SetMyHosts.sh
> 
> !/bin/sh
> 
> create my custom dnsmasq file
> cat > /run/dnsmasq.conf.d/mine.conf <<EOF
> host-record=udmp,gateway,192.168.1.1
> host-record=host111,192.168.1.99
> EOF
> 
> force restart of dnsmasq
> pkill dnsmasq
> 
> This will work across reboots & firmware upgrades (but not factory resets).
> I threw in the udmp & gateway line to show an example of multiple hostnames mapping to the same ip.
> To run the script without rebooting:
> 
> sh /mnt/data/on_boot.d/10SetMyHosts.sh
> I recommend that you keep a copy of the script somewhere off the UDMP in case you have to do a factory reset one day.
> 
> **2. [MDNS](https://hub.docker.com/r/scyto/multicast-relay)**
> 
> **3. [DNS masquerade](https://github.com/boostchicken/udm-utilities/blob/master/dns-common/on_boot.d/10-dns.sh)**
> set this to the interface(s) on which you want DNS TCP/UDP port 53 traffic
> re-routed through the DNS container. separate interfaces with spaces.
> e.g. "br0" or "br0 br1" etc.
> FORCED_INTFC=""
> 
> Dit you even read the instructions or text on the main page? This is all available for a long time.

1 & 2 are clear to me
But with 3 it's not my intention to route all dns traffic to a dns container, in my existing gateway.config.json I made nat routing for my vlans for when a device tries to connect to dns port who is not one of my 2 PïHole's, and then the masquerade rules are used so the device is not aware that it is beign routed to PiHole instead of Google dns etc.

It's this sectional I would like to now a way to implement on the UDM Pro, also I want to keep using my 2 RasPi with PiHole instead of running PiHole on a container:

```
nat": {
      "rule": {
        "10": {
          "description": "Redirect Trusted VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.10",
          "inside-address": {
            "address": "10.10.10.5-10.10.10.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.10.5-10.10.10.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
		"20": {
          "description": "Redirect IoT VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.20",
          "inside-address": {
            "address": "10.10.20.5-10.10.20.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.20.5-10.10.20.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
		"30": {
          "description": "Redirect Guests VLAN DNS requests",
          "destination": {
            "port": "53"
          },
          "inbound-interface": "eth1.30",
          "inside-address": {
            "address": "10.10.30.5-10.10.30.6",
            "port": "53"
          },
          "source": {
            "address": "!10.10.30.5-10.10.30.6"
          },
          "log": "disable",
          "protocol": "tcp_udp",
          "type": "destination"
        },
        "6010": {
          "description": "MASQ Trusted VLAN DNS requests",
          "destination": {
            "address": "10.10.10.5-10.10.10.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.10",
          "protocol": "tcp_udp",
          "type": "masquerade"
        },
        "6020": {
          "description": "MASQ IoT VLAN DNS requests",
          "destination": {
            "address": "10.10.20.5-10.10.20.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.20",
          "protocol": "tcp_udp",
          "type": "masquerade"
		},
        "6030": {
          "description": "MASQ Guests VLAN DNS requests",
          "destination": {
            "address": "10.10.30.5-10.10.30.6",
            "port": "53"
          },
          "log": "disable",
          "outbound-interface": "eth1.30",
          "protocol": "tcp_udp",
          "type": "masquerade"  
		}

```

**Comment by renedis** [comment]
> But with 3 it's not my intention to route all dns traffic to a dns container, in my existing gateway.config.json I made nat routing for my vlans for when a device tries to connect to dns port who is not one of my 2 PïHole's, and then the masquerade rules are used so the device is not aware that it is beign routed to PiHole instead of Google dns etc.
> 
> It's this sectional I would like to now a way to implement on the UDM Pro, also I want to keep using my 2 RasPi with PiHole instead of running PiHole on a container:


The script is not redirecting to a container, but to a IP address. You can remove the extra bits in the script to keep only the masquerade part.

Should look something like this for 1 pihole IP:

`#!/bin/sh

# IPv6 Also works with Prefix Delegation from your provider. The gateway is the
# IP of br(VLAN) and you can pick any ip address within that subnet that dhcpv6
# isn't serving
IPV6_IP=""
IPV6_GW=""

# set this to the interface(s) on which you want DNS TCP/UDP port 53 traffic
# re-routed through the DNS container. separate interfaces with spaces.
# e.g. "br0" or "br0 br1" etc.
FORCED_INTFC=""

# (optional) IPv4 force DNS (TCP/UDP 53)
for intfc in ${FORCED_INTFC}; do
  if [ -d "/sys/class/net/${intfc}" ]; then
    for proto in udp tcp; do
      prerouting_rule="PREROUTING -i ${intfc} -p ${proto} ! -s ${IPV4_IP} ! -d ${IPV4_IP} --dport 53 -j DNAT --to ${IPV4_IP}"
      iptables -t nat -C ${prerouting_rule} || iptables -t nat -A ${prerouting_rule}
      
      # (optional) IPv6 force DNS (TCP/UDP 53)
      if [ -n "${IPV6_IP}" ]; then
        prerouting_rule="PREROUTING -i ${intfc} -p ${proto} ! -s ${IPV6_IP} ! -d ${IPV6_IP} --dport 53 -j DNAT --to ${IPV6_IP}"
        ip6tables -t nat -C ${prerouting_rule} || ip6tables -t nat -A ${prerouting_rule}
      fi
    done
  fi
done`

**Comment by Tntdruid** [comment]
Can you do that whit more than 1 IP?

**Comment by Kopernikus1979** [comment]
Yes, also wondering how to do this for my second Pihole? Should I add a second script?
Also with FORCED_INTFC="" should I define here every VLAN?

Now my Pi-Hole's are multihomed meaning they have an IP in every VLAN, but thinking of moving them to my Management VLAN1, the reason for this is because I read somewhere when you forwareded ip is not in the same subnet of your pihole the dnsmasq rule is not needed, is this correct?

**Comment by boostchicken** [comment]
you can do this for any ip address, just make a new script like "99-iptables.sh" and then have it contain all your ip tables execs yuou want there.

**Comment by boostchicken** [comment]
Also, ditch multi homed.that is one reason for sure.

**Comment by Kopernikus1979** [comment]
> 
> 
> Also, ditch multi homed.that is one reason for sure.

Thx, did you mean by "one reason for sure" that by ditching the multihomed I don't need the dnsmasq rule?

**Comment by EntropySmoke** [comment]
A bit off-topic, but does UDM accept and honor all CLI commands that USG accepts and honors via config.gateway.json and/or CLI? Some commands don't seem to work at all for UDM. For example, Ubiquiti's CLI commands to stop LLDP (Link Layer Discovery Protocol) advertisement do not stop it. It may be a bug, but it is unknown to me.

Another example is:
set service ubnt-discover disable
set service ubnt-discover-server disable

UDM does not honor those commands and continues to perform device discovery via broadcast IP 255.255.255.255 UDP port 10001 (over LAN and even WAN), but developers say that it is a known bug in new firmware releases.

**Comment by EntropySmoke** [comment]
Any luck with your conversion? I think the config file for UDM is the /config/ubios-udapi-server/ubios-udapi-server.state .

**Comment by Kopernikus1979** [comment]
All is working fine, however can't seem to get my seond PiHole working:

I have:

iptables -t nat -A PREROUTING -i br0 -p udp ! -s 10.10.1.5 ! -d 10.10.1.5 --dport 53 -j DNAT --to 10.10.1.5:53

but if I create a second script for:

iptables -t nat -A PREROUTING -i br0 -p udp ! -s 10.10.1.6 ! -d 10.10.1.6 --dport 53 -j DNAT --to 10.10.1.6:53

the second script will be ignored if I have a dns lookup on the second PiHole

In gateway.config.json I could set as source !10.10.1.5-10.10.1.6 and as destination 10.10.1.5-10.10.1.6

How to acomplish this? I can ofcourse ditch the second PiHole....

Thx

**Comment by oliversl** [comment]
Directory /mnt/data/on_boot.d/ does not existe anymore as of firmware from today

**Comment by untergeek** [comment]
@oliversl which firmware is that? I upgraded my UDM Pro to 1.12.30 several days ago and `/mnt/data/on_boot.d/` is very much still there and worked at startup for me.

**Comment by Jiriteach** [comment]
1.12.30 is the latest even for early adopter and all working for me.

**Comment by oliversl** [comment]
My fault, looks like the folder /mnt/data/on_boot.d/ is created by a custom user script. On a vanilla UDM SE,  in the /mnt/data/ folder, there is no on_boot.d folder.

**Comment by crsang** [comment]
I'm still struggling with making this work on the UDMP.  @Kopernikus1979 where you able to find a scripted solution?

**Comment by Kopernikus1979** [comment]
Edited my post with the scripts

**Comment by boostchicken** [comment]
Wow, thanks for coming back after all this time.  Feel free to send a PR to the repo with your scripts!

**Comment by crsang** [comment]
@Kopernikus1979 Did you have to add a rule to the UDM to allow VRRP traffic?  My keepalived is flapping between master/backup.

**Comment by crsang** [comment]
I removed the unicast lines from your keepalived configs and the flapping stopped.  Not sure why multicast works and unicast did not.

**Comment by Kopernikus1979** [comment]
@crsang 

Hi,

No rule, but both my pihole's are on their own Pi-Hole VLAN.
