### ISSUE TITLE
pihole no longer runs since newest update

### ISSUE THREAD

**Issue by justfly1111** [unifi-utilities/unifios-utilities#307]
so i was running pihole-dote flawlessly for  awhile then after a reboot it drew from the latest pihole docker build and now the container looks like it starts and runs but nothing when u go to the web ui and when you try to podman exec -it pihole bash you get the oci error and it kicks you immeadately out i dont remember which version of pihole was working last or id use it instead of latest so i tried to pull from boostchicken/pihole:latest instead and same exact issue and pihole is completely unoperable on my system anyone else having simular issues or remember the last versuib of pihole that was flawlessly working?

**Comment by lillycat12** [comment]
What version of podman?

**Comment by JoeOIVOV** [comment]
Yes,  I had dote working perfectly for last few months and then all of a sudden, I cannot get any dote version working I tried at least 3 different builds.
After I revert to DOH version, it works as expected...  waiting to hear why, I'm not quite sure what changed to cause this issue as well...

**Comment by JoeOIVOV** [comment]
> What version of podman?

1.6.1

**Comment by nau88xj** [comment]
I just ran into this on a fresh install.  I had luck running the custom_pihole_dote.sh
[Go to file](https://github.com/boostchicken-dev/udm-utilities/find/1adccdb2357fd2e85b7b3d22d2f075574275516f) script to launch the container instead.

**Comment by boostchicken** [comment]
fixed
