### ISSUE TITLE
Persisted path wrong

### ISSUE THREAD

**Issue by thezim** [unifi-utilities/unifios-utilities#336]
Looking at udm-boot.service file that is generated from remote_install.sh I see /mnt/data is used (hard coded) has the [persisted path](https://github.com/boostchicken-dev/udm-utilities/blob/1adccdb2357fd2e85b7b3d22d2f075574275516f/on-boot-script/remote_install.sh#L131), however on the UDM SE the persisted path is /data. Later in the script actual persisted path as returned by get_persistent_path is used to look for CNI plug-in which will not match.

Was this by design or was the by error?

**Comment by boostchicken** [comment]
Fixed
