### ISSUE TITLE
/etc/cni/net.d/dns.conflist gets wiped on reboot

### ISSUE THREAD

**Issue by TaiSHiNet** [unifi-utilities/unifios-utilities#340]
**Describe the bug**
/etc/cni/net.d/dns.conflist gets wiped on reboot, causing 05-install-cni-plugins.sh to fail

**To Reproduce**
Followed steps to set everything on my UDM Pro and rebooted

**Expected behavior**
/mnt/data/podman/cni/dns.conflist should persist across reboots

**UDM Information**
 - UDM Pro
 - Firmware Version: 1.11.4
 - Controller Version 7.0.3

I fixed it by dropping the file to `/mnt/data/podman/cni/` and adding a symlink item on `05-install-cni-plugins.sh`

**Comment by jgstroud** [comment]
I'm on 1.12.15 / 7.1.59 and can confirm this issue.  I added the same workaround.

**Comment by adm746** [comment]
I have this problem on UDM 1.11.4. However it looks like 05-install-cni-plugins.sh has the symlink code already:

`# Insert conf files for podman networks into the net.d folder                   
populate_netd()                                                                 
{                                                                               
  for file in "${CNI_NETD}"/*.conflist                                          
  do                                                                            
    if [ -f "$file" ]; then                                                     
        ln -fs "$file" "/etc/cni/net.d/$(basename "$file")"                     
    fi                                                                          
  done                                                                          
} `

which is run in the final script line. Simply placing dns.conflist in /mnt/data/podman/cni/ without adding a symlink item fixed this issue for me. The run-pihole readme should be updated to include putting dns.conflist in /mnt/data/podman/cni/ and running  05-install-cni-plugins.sh after to establish the symlink
