### ISSUE TITLE
Permission denied running scripts

### ISSUE THREAD

**Issue by dgaz9** [unifi-utilities/unifios-utilities#354]
I am receiving a permission denied when running the scripts per the instruction. 

./30-ipt-enable-logs-launch.sh: line 6: /mnt/data/scripts/ipt-enable-logs.sh: Permission denied

# ls -l
total 16
-rwxr-xr-x    1 root     root          4780 Apr 21 09:37 05-install-cni-plugins.sh
-rwxr-xr-x    1 root     root           138 Apr 21 09:37 06-cni-bridge.sh
-rwxr-xr-x    1 root     root           232 Apr 21 10:43 30-ipt-enable-logs-launch.sh

I appreciate any assistance.

**Comment by alxwolf** [comment]
What does `ls -l /mnt/data/scripts` say?

**Comment by dillionbender** [comment]
> 

# cd /mnt/data/scripts/
# ls -l
total 8
drwxr-xr-x    2 root     root          4096 Apr 21 11:50 ipt-enable-logs
-rw-r--r--    1 root     root           214 Apr 21 11:50 ipt-enable-logs.sh

**Comment by alxwolf** [comment]
Run a `chmod +x /mnt/data/scripts/ipt-enable-logs.sh` and it should run fine. The script is not set as executable right now.

**Comment by dillionbender** [comment]
That worked perfectly! thank you. However now when i try to follow the logs using the logunifi function i am not getting anything. i provide the password then nothing happens.

I have tried generating traffic without luck. Does this also provide these tags for syslog being sent syslog?

**Comment by dgaz9** [comment]
![Capture](https://user-images.githubusercontent.com/80014909/164761452-e786d0ca-81d5-4262-877a-8dc82d74a364.PNG)

**Comment by alxwolf** [comment]
Well, the final output of `logunifi` should look like this:

```
user@machine  ~  logunifi
Welcome to UbiOS

By logging in, accessing, or using the Ubiquiti product, you
acknowledge that you have read and understood the Ubiquiti
License Agreement and agree to be bound by its terms.

Apr 22 19:32:51 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.220@49666DST=10.254.254.254@57572	LEN=61	
Apr 22 19:32:52 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.220@49666DST=10.254.254.254@57572	LEN=61	
Apr 22 19:32:54 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.155@63467DST=10.254.254.254@57572	LEN=61	
Apr 22 19:32:55 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.155@63467DST=10.254.254.254@57572	LEN=61	
Apr 22 19:32:59 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.182@49666DST=10.254.254.254@57572	LEN=61	
Apr 22 19:32:59 - FW-D-LAN_IN_U-4000	IN=br100  	UDP	SRC=192.168.100.182@49666DST=10.254.254.254@57572	LEN=61	
```

You could check that by logging into your UDM, tell it to `tail -f /var/log/messages` and amongst other it should show (here matching to above "shorthand"):

```
Apr 22 19:32:51 ubnt user.warn kernel: [1452890.960350] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:14:7d:da:db:6a:9e:08:00 SRC=192.168.100.220 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=10265 PROTO=UDP SPT=49666 DPT=57572 LEN=61 
Apr 22 19:32:52 ubnt user.warn kernel: [1452891.466778] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:14:7d:da:db:6a:9e:08:00 SRC=192.168.100.220 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=37957 PROTO=UDP SPT=49666 DPT=57572 LEN=61 
Apr 22 19:32:54 ubnt user.warn kernel: [1452893.955878] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:2a:4c:aa:1a:c4:3b:08:00 SRC=192.168.100.155 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=21906 PROTO=UDP SPT=63467 DPT=57572 LEN=61 
Apr 22 19:32:55 ubnt user.warn kernel: [1452894.959214] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:2a:4c:aa:1a:c4:3b:08:00 SRC=192.168.100.155 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=58695 PROTO=UDP SPT=63467 DPT=57572 LEN=61 
Apr 22 19:32:59 ubnt user.warn kernel: [1452898.304938] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:3c:e1:a1:44:70:cc:08:00 SRC=192.168.100.182 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=38471 PROTO=UDP SPT=49666 DPT=57572 LEN=61 
Apr 22 19:32:59 ubnt user.warn kernel: [1452898.304988] [FW-D-LAN_IN_U-4000] IN=br100 OUT=eth8 MAC=74:ac:b9:d9:52:07:3c:e1:a1:44:70:cc:08:00 SRC=192.168.100.182 DST=10.254.254.254 LEN=81 TOS=0x00 PREC=0x00 TTL=63 ID=32099 PROTO=UDP SPT=49666 DPT=57572 LEN=61 
```

Looks like right now you don't have any traffic stopped by the firewall. If nothing shows up in `/var/log/messages`, you could try activating the logs for the standard rules (and you should get swamped by messages...)

**Comment by dgaz9** [comment]
Do you run the logunifi command on your UDMP or from another machine?

**Comment by alxwolf** [comment]
From another machine. The command will `ssh` into UDM/P and do its thing.

looking at your screenshot, it seems like the "rg" command tries to run on your local machine - and is not installed.

How does your bash script look like? please check that for any lost backslashes or pipe symbols...

```
function logunifijson() {
  ssh <the name or IP of your UDM/P> "tail -f /var/log/messages" | \
    rg "kernel:" | \
    sed "s/]IN/] IN/" | \
    jq --unbuffered -R '. | rtrimstr(" ") | split(": ") | {date: (.[0] | split(" ") | .[0:3] | join(" "))} + (.[1] | capture("\\[.+\\] \\[(?<rule>.*)\\].*")) + ((.[1] | capture("\\[.+\\] (?<rest>.*)") | .rest | split(" ") | map(select(startswith("[") == false) | split("=") | {(.[0]): .[1]})) | (reduce .[] as $item ({}; . + $item)))'
}

function logunifi() {
  logunifijson | jq --unbuffered -r '"\(.date) - \(.rule)\tIN=\(.IN)  \t\(.PROTO)\tSRC=\(.SRC)@\(.SPT)\tDST=\(.DST)@\(.DPT)\tLEN=\(.LEN)\t"'
}
```

**Comment by dgaz9** [comment]
Ok so i found the logs. What is interesting is they are not in /var/log/messages but in /var/log/iptables instead. This is ok since i know where they are. However in your example and my logs i do not see the action being taken in each log. Unless i am missing somthing? Also how to i export the /var/log/iptables logs via syslog?

**Comment by alxwolf** [comment]
let me guess you're running EA version 1.12.15?

UI is having fun with us changing the location back and forth:

release notes from:

V 1.12.15: "Save firewall log in "/var/log/iptables."
V 1.12.19: "Save firewall log in /var/log/messages with informational prefix." (sic!)

So maybe this workaround is not required anymore - soon.

**Comment by alxwolf** [comment]
On your question about syslog: the UDM/P sends in BSD, on UDP/514 (or any other port you provide).

to send to a remote device, **do not** enable the *Syslog & Netconsole Logs* setting.

**Comment by alxwolf** [comment]
So: installed the Early Access Firmware and now logs report with prefix.


```
| user | kernel | [ 300.694857] [LAN_IN-RET-2000] IN=br0 OUT=br100 MAC= ...

```

we may be able to stop using the (good) workaround. Let's wait for the release version.
