### ISSUE TITLE
run-pihole - Error at container startup with s6-overlay

### ISSUE THREAD

**Issue by nerthazrim** [unifi-utilities/unifios-utilities#403]
Hi,

I've followed the steps of the tutorial https://github.com/unifi-utilities/unifios-utilities/tree/main/run-pihole

However, when the pihole container is starting, the logs are as follow:

$ podman logs pihole
/package/admin/s6-overlay-3.1.1.2/libexec/stage0: 79: exec: /run/s6/basedir/bin/init: Permission denied
/package/admin/s6-overlay-3.1.1.2/libexec/stage0: 79: exec: /run/s6/basedir/bin/init: Permission denied
/package/admin/s6-overlay-3.1.1.2/libexec/stage0: 79: exec: /run/s6/basedir/bin/init: Permission denied
/package/admin/s6-overlay-3.1.1.2/libexec/stage0: 79: exec: /run/s6/basedir/bin/init: Permission denied
[...]

Am I missing something?

UniFi OS UDM Pro 1.12.22
UniFi Network 7.2.92

$ podman version
Version:            1.6.1
RemoteAPI Version:  1
Go Version:         go1.12.10
OS/Arch:            linux/arm64

Many thanks in advance for the help, I could not find any helpful information either here or on third-party forums :(

**Comment by imrobertson** [comment]
Same issue here. I believe my UDMP updated and KERPLONK....Pihole now fails. Have updated per the upd_pihole but no joy.

**Comment by mlankamp** [comment]
don't use the latest, but use `2022.07.1` as the tag

**Comment by nerthazrim** [comment]
Awesone!

Thanks @mlankamp it works indeed!

Do you know when we'll be able to use the "latest" tag? Or what do we need to do to be able to?

**Comment by jsermer** [comment]
They have an experimental fix for the issue upstream.  It works for me now:

https://github.com/pi-hole/docker-pi-hole/issues/1176#issuecomment-1227635376

**Comment by nerthazrim** [comment]
Thanks!

Is there a way to change the tag of a container without losing everything in it and have to reconfigure everything?

**Comment by PromoFaux** [comment]
If it is working, then we can tag `pihole/pihole:2022.08.2`, which will become `latest`

**Comment by nerthazrim** [comment]
I'm not seasoned in docker/podman.
Would you be so kind to give the commands/procedure to upgrade the tag (and therefore the container) without losing the configuration in the current one?

**Comment by castles** [comment]
Have a look at what [mlankamp](https://github.com/mlankamp) posted above. That's how to set your tag in the upgrade script.

**Comment by nerthazrim** [comment]
How so if I pull the pihole container but with another tag, it'll update my "current" one with all my config in it?
It's not going to start another container in parallel?

Good to know, thanks!

**Comment by castles** [comment]
Yeah, I wasn't sure myself but it worked for me. Thanks [mlankamp](https://github.com/mlankamp)

**Comment by mlankamp** [comment]
You can update to tag `:2022.08.2` this contains the fix (or go back to latest)

**Comment by mlankamp** [comment]
The problem is fixed, see https://github.com/pi-hole/docker-pi-hole/issues/1176#issuecomment-1228268198

**Comment by nerthazrim** [comment]
Indeed, I can confirm! Thanks a lot!
