### ISSUE TITLE
Podman builds expired

### ISSUE THREAD

**Issue by bdavj** [unifi-utilities/unifios-utilities#421]
It seems the podman builds in the repo have expired - can these be rebuilt?

**Comment by scoutbeer** [comment]
Also wondering how to download the builds now that they are expired...

**Comment by bdavj** [comment]
I ended up forking it and building - welcome to pull it down from the action output [Here](https://github.com/bdavj/unifios-utilities/actions)

**Comment by jgenender** [comment]
Thanks for doing that... at least its another spot to grab the artifact!

**Comment by hardselius** [comment]
Why not just run the podman builds on a schedule and not have to worry about this ever again?
