### ISSUE TITLE
Shell installation does not work

### ISSUE THREAD

**Issue by ruben375** [unifi-utilities/unifios-utilities#422]
**Describe the bug**
If I want to install the remot_install.sh on my UniFi OS UDM SE 2.5.11 with the following syntax as proposed on the website (github link had to be updated): 

curl -fsL "https://github.com/unifi-utilities/unifios-utilities/tree/main/on-boot-script/remote_install.sh" | /bin/sh

I get the following error message on Putty: "Error while cleaning up" (Please refer to the screenshot below).

How can I make it work?

**To Reproduce**
1. Go to Putty
2. Login to UDM-SE
3. Enter the command line orders according to screenshot

**Expected behavior**
unclear

**Screenshots**
![image](https://user-images.githubusercontent.com/96666343/193567028-cd2efc75-af10-4863-bbbe-028cd12d276c.png)

**UDM Information**
 - Variant UDM-SE
 - Firmware Version: 2.5.11
![image](https://user-images.githubusercontent.com/96666343/193567717-231e5751-f009-4a3d-9e53-bd0b90946409.png)

**Additional context**

**Comment by boostchicken** [comment]
Please reopen if still an issue
