### ISSUE TITLE
Podman for UDM SE archive has expired

### ISSUE THREAD

**Issue by kevinv11n** [unifi-utilities/unifios-utilities#427]
**Describe the bug**
Podman for UDM SE zip isn't available.

**To Reproduce**
1. Go to https://github.com/unifi-utilities/unifios-utilities#custom-podman-builds-for-udm-se and observe it says to download the Podam for UDM SE installer from https://github.com/unifi-utilities/unifios-utilities/actions
2. This leads the user to https://github.com/unifi-utilities/unifios-utilities/actions/runs/2551133100
3. Observe that the built archive is expired so can't be downloaded.

**Expected behavior**
The archive should be available for download

**Comment by kevinv11n** [comment]
Re-running the action should produce a new archive. @boostchicken  I imagine you're one of few people with perms to do this.

**Comment by medfear** [comment]
See discussion 
https://github.com/unifi-utilities/unifios-utilities/discussions/419
for a solution.
