### ISSUE TITLE
Initial UDM SE Podman installation

### ISSUE THREAD

**Issue by llaforest** [unifi-utilities/unifios-utilities#432]
I'm trying to setup podman on my new UDM SE running 2.5.11. I'm very confused because I cannot find a clear path to initial install. 
I tried to follow issue 419 and run the '01-podman-update.sh' after I replaced the '/mnt/data' by '/data' but the script seems to assume there is a podman already installed. I understand it's named as update script but what do I do if I have fresh console.

From issue 384, when instructions say to get the latest zip archive from the action tab, but they are all expired. It also seems to assume that podman is installed.

My final goal is to be able to setup the ubios-cert to manage issuing and renewal of my certificates. It used to work on UDM Pro but it seems to require podman to run acme.sh.

I will try to run the cert script without podman because it seems podman will not survive a firmware update. This means my certificates would stop generating and I would need to redeploy some stuff...

If someone knows the clear path for the noob I am, I would appreciate!

Cheers!

**Comment by SirUli** [comment]
Hi @llaforest,

i blogged about that installation a while back: https://wolf-u.li/en/unifi-dream-router-udr-setup-of-podman/

Hope that helps.

**Comment by llaforest** [comment]
Wow what a nice procedure you made there!! Here is a curl command that can fetch the zip file from the UDR directly instead of having to winscp it. It will always get the latest one.

`curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <github_token>" \
  -o udmse-podman-install.zip \
  "https://api.github.com/repos/unifi-utilities/unifios-utilities/actions/artifacts/$(curl -s \
    -H "Accept: application/vnd.github+json" \
    https://api.github.com/repos/unifi-utilities/unifios-utilities/actions/artifacts?name="udmse-podman-install.zip" | \
    jq '.artifacts[0].id')/zip"`

And this is what I did to get this token:
Go here:  https://github.com/settings/tokens
Click on Generate New Token --> Generate New Token (Classic)
Give it a note such as: “Public Repo Download”
Set the expiration (I put no expiration as it has almost no rights)
Select only “public_repo” near the top
Generate and save the token because it cannot be seen anymore

**Comment by llaforest** [comment]
Is there a reason why I get this error when trying to run 'podman ps':
```
Error: could not find a working conmon binary (configured options: [/usr/libexec/podman/conmon /usr/local/libexec/podman/conmon /usr/local/lib/podman/conmon /usr/bin/conmon /usr/sbin/conmon /usr/local/bin/conmon /usr/local/sbin/conmon /run/current-system/sw/bin/conmon]): invalid argument
```

**Comment by sprintman** [comment]
@SirUli, the instructions you provided have
```
mkdir -p /data/on_boot.d/
mv /data/on_boot.d/* /data/on_boot.d/
mv /data/.cache /data/
rm -Rf /data
ln -snf /data /data
```
I presume that shoud be
```
mkdir -p /data/on_boot.d/
mv /mnt/data/on_boot.d/* /data/on_boot.d/
mv /mnt/data/.cache /data/
rm -Rf /mnt/data
ln -snf /data /mnt/data
```
I don't want to test what the effects of `rm -Rf /data` would be

**Comment by SirUli** [comment]
@sprintman thanks for the nice catch, much appreciated. Will be fixed in a couple minutes.
