### ISSUE TITLE
UDM Pro adguard won't start after reboot

### ISSUE THREAD

**Issue by dbbdark1990** [unifi-utilities/unifios-utilities#446]
Adguardhome runs fine after UDM pro reboot it won't start i get :

 *# podman ps
CONTAINER ID  IMAGE                      COMMAND     CREATED      STATUS            PORTS  NAMES
ff05a31585f9  localhost/unifi-os:latest  /sbin/init  5 weeks ago  Up 2 minutes ago         unifi-os
*# podman container start adguardhome
ERRO[0000] Error adding network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]
ERRO[0000] Error while adding to cni lo network: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]
Error: unable to start container "adguardhome": error configuring network namespace for container c5c6dc0f805ce71add75e74893e7877e4ceb56781ead1e5f9dd9fe310e09ede8: failed to find plugin "loopback" in path [/usr/libexec/cni /usr/lib/cni /usr/local/lib/cni /opt/cni/bin]`

Info :

Unifi os : 1.12.33
Network: 7.3.76

*# cd /mnt/data/on_boot.d/
*# ls -all
total 28
drwxrwxrwx    2 root     root          4096 Dec 11 10:06 .
drwxr-xr-x   16 root     root          4096 Dec 11 09:50 ..
-rwxrwxrwx    1 root     root          5086 Dec 11 10:11 05-install-cni-plugins.sh
-rwxrwxrwx    1 root     root           138 Dec 11 10:06 06-cni-bridge.sh
-rwxrwxrwx    1 root     root          4228 Dec 11 10:07 10-dns.sh
*# cd /mnt/data/podman/
cni/      storage/
*# cd /mnt/data/podman/cni/
*# ls -all
total 12
drwxr-xr-x    2 root     root          4096 Dec 10 16:31 .
drwx------    4 root     root          4096 Dec 10 13:40 ..
-rw-r--r--    1 root     root           390 Dec 11 10:05 20-dns.conflist
*#

Manully fix:

1; curl -fsL "https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/HEAD/on-boot-script/remote_install.sh" | /bin/sh
2; /mnt/data/on_boot.d/05-install-cni-plugins.sh
3; /mnt/data/on_boot.d/10-dns.sh
4; podman container start adguardhome

Everythings running fine

**Comment by Postman76** [comment]
Noticed a similar issue today with UDM Pro and with version 2.4.23. Everything has been working nicely few years so far, but not anymore.

Only difference is that the whole /mnt/data/ folder is gone and therefore anything on on_boot scripts are obviously not starting. I cannot re-install anymore where podman support is gone from this version.

Maybe it is time to move adguard for my spare Pi, instead of UDM Pro.

**Comment by boostchicken** [comment]
You didnt make a custom dnsconflist called adguardhome.  Look at 10-dns.sh.  It looks for conflists files then setups them up.
