### ISSUE TITLE
Boostchicken Pihole builds fails to start

### ISSUE THREAD

**Issue by Hengjie** [unifi-utilities/unifios-utilities#447]
On the latest `2022.11.2` builds of boostchicken:pihole image, starting it up gets the following:

```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
cont-init: info: running /etc/cont-init.d/10-cloudflared.sh
/package/admin/s6-overlay-3.1.1.2/etc/s6-rc/scripts/cont-init: 14: /etc/cont-init.d/10-cloudflared.sh: Permission denied
cont-init: info: /etc/cont-init.d/10-cloudflared.sh exited 126
cont-init: warning: some scripts exited nonzero
s6-rc: warning: unable to start service legacy-cont-init: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

Note the lines around `10-cloudflared.sh: Permission denied`. 

**To Reproduce**
The builds beyond 2022.07.1 do not appear to work. 

**Expected behavior**
For it to start up without failures. 

Based on https://webcache.googleusercontent.com/search?q=cache:JGVbO_IhHy8J:https://www.devscope.io/code/unifi-utilities/unifios-utilities/issues/425&cd=1
> This looks like a result of the https://github.com/pi-hole/docker-pi-hole repo reorganizing some files from 2022.07.1 to 2022.8.3 and above.
> In 2022.8.3 and above there is no /etc/conf-init.d folder... looks like the repo changed the way startup processes work moving from S6_OVERLAY_VERSION v2.1.0.2 in 2022.07.01 to S6_OVERLAY_VERSION v3.1.1.2 in 2022.08.03 and above

**Comment by Hengjie** [comment]
Actually, this is fixed in PR https://github.com/unifi-utilities/unifios-utilities/pull/439 but the docker builds for the fix has yet to land. So I won't close this issue yet.

**Comment by boostchicken** [comment]
I will fix this now
