### ISSUE TITLE
Podman 4.3 issues UDM-SE 2.5.11

### ISSUE THREAD

**Issue by sprintman** [unifi-utilities/unifios-utilities#448]
Two issues with the UDM-SE Podman 4.3 build on UnifiOS 2.5.11

I get an error `WARN[0000] Failed to read current user namespace mappings` every time I run a podman command. This doesn't appear to be causing any problems in my setup.

Containers using macvlan initially start up fine. After a period of time (hours?) the container loses the macvlan interface. Reloading the network for the container fails. Removing and recreating the container works for a period of time.
```
root@UDM-SE:~# podman exec pihole ip a
WARN[0000] Failed to read current user namespace mappings
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: gre0@NONE: <NOARP> mtu 1476 qdisc noop state DOWN group default qlen 1000
    link/gre 0.0.0.0 brd 0.0.0.0
3: gretap0@NONE: <BROADCAST,MULTICAST> mtu 1462 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
4: erspan0@NONE: <BROADCAST,MULTICAST> mtu 1450 qdisc noop state DOWN group default qlen 1000
    link/ether 00:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
5: ip_vti0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/ipip 0.0.0.0 brd 0.0.0.0
6: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
root@UDM-SE:~# podman network reload pihole
WARN[0000] Failed to read current user namespace mappings
WARN[0000] Failed to load cached network config: network dns not found in CNI cache, falling back to loading network dns from disk
WARN[0000] Failed to load cached network config: network dns not found in CNI cache, falling back to loading network dns from disk
Error: plugin type="macvlan" failed (add): cni plugin macvlan failed: an entry in the 'ips' field is NOT in CIDR notation, got: '10.2.0.2'
```
I downgraded to Podman 3.4.4 and everything works fine.

**Comment by KevLille** [comment]
Same error for me with UDM SE v3.0.13

**Comment by bennettp123** [comment]
Same issue here on UDM (base) v2.4.23

I think there have been some changes in podman 4; it looks like it doesn't support the `static` ipam driver any more—or at least it's not compatible.

I managed to get it working using the default ipam driver:

```bash
# remove the dns network
podman network rm -f dns

# create a new dns network
podman network create \
  -d macvlan \
  -o parent=br5 \
  -o mode=bridge \
  --subnet 10.0.5.0/24 \
  --ip-range 10.0.5.3/32 \
  --gateway 10.0.5.1 \
  dns
```

This produced `/etc/cni/net.d/dns.conflist`:

```json
{
   "args": {
      "podman_options": {
         "mode": "bridge"
      }
   },
   "cniVersion": "0.4.0",
   "name": "dns",
   "plugins": [
      {
         "type": "macvlan",
         "master": "br5",
         "ipam": {
            "type": "host-local",
            "routes": [
               {
                  "dst": "0.0.0.0/0"
               },
               {
                  "dst": "::/0"
               }
            ],
            "ranges": [
               [
                  {
                     "subnet": "10.0.5.0/24",
                     "rangeStart": "10.0.5.3",
                     "rangeEnd": "10.0.5.3",
                     "gateway": "10.0.5.1"
                  }
               ],
            ]
         },
         "mode": "bridge",
         "capabilities": {
            "ips": true
         }
      }
   ]
}
```

I modified `/data/podman/cni/20-dns.conflist` to match the contents above, deleted the network, re-ran `05-install-ini-plugins.sh` (to make sure it recreates the network ok), and finally restart pihole:

```bash
cat /etc/cni/net.d/dns.conflist > /data/podman/cni/20-dns.conflist
podman rm -f dns
/data/on_boot.d/05-install-cni-plugins.sh
/data/scripts/upd_pihole.sh
```

It seems to be working ok for now. I'll keep an eye on it, and revert to podman 3.x if there are any issues.

**Comment by bennettp123** [comment]
Oh and it should be ok to ignore the warning—it's generated by the [`IsRootless` function](https://github.com/containers/storage/blob/0e0cab009547e3521fd286096cdaa0a46b9e4b04/pkg/unshare/unshare_linux.go#L425) on linux— it checks for uid/gid mappings using [`/proc/self/uid_map`](https://github.com/containers/storage/blob/0e0cab009547e3521fd286096cdaa0a46b9e4b04/pkg/unshare/unshare_linux.go#L392), but the UDM kernel is compiled without `CONFIG_USER_NS` so it always raises the warning.

However, as long as you're running podman as root, you shouldn't be affected.
