### ISSUE TITLE
Support for UDM(P) 2.4.x 

### ISSUE THREAD

**Issue by bananaman2020** [unifi-utilities/unifios-utilities#450]
Unifi just released EA firmware for the UDM base and UDMP. https://community.ui.com/releases/UniFi-OS-Dream-Machines-2-4-23/aebbba64-9e7e-4151-bcca-34ed08761f08 This update is the migration to 2.4.x. The current UDMP scripts don't work with this firmware mainly because of the removal of podman. Updated instructions would help greatly

**Comment by owine** [comment]
Being discussed in #416
