### ISSUE TITLE
ipfs resolve -r /ipns/unifi.boostchicken.io/: could not resolve name

### ISSUE THREAD

**Issue by adam-skalicky** [unifi-utilities/unifios-utilities#455]
Hi There,

I am unable to download the UDM SE install files from IPFS - I get an error stating **ipfs resolve -r /ipns/unifi.boostchicken.io/: could not resolve name**

![image](https://user-images.githubusercontent.com/52025062/208316889-16fbe888-122e-4978-b3f5-4b32008511f5.png)

My apologies in advance if IPFS requires some specific client, but from what I read it looks like it should work over HTTP.

**Comment by adam-skalicky** [comment]
Tagging @boostchicken because I suspect you own the endpoint if it is in fact down.

**Comment by boostchicken** [comment]
Server isb ack!
