### ISSUE TITLE
udm-boot 1.0.6 will not install on UDMp

### ISSUE THREAD

**Issue by cybik** [unifi-utilities/unifios-utilities#472]
**Describe the bug**
The udm-boot 1.0.6 package seems to have an unrecognized compression:

```
root@router:/data/manual/workspace# dpkg -i udm-boot_1.0.6_all.deb 
dpkg-deb: error: archive 'udm-boot_1.0.6_all.deb' uses unknown compression for member 'control.tar.zst', giving up
dpkg: error processing archive udm-boot_1.0.6_all.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 udm-boot_1.0.6_all.deb
```

I suspect that the package was generated on too "recent" a Ubuntu node. The UDMp's apt is old:

```root@router:/data/manual/workspace# dpkg --version
Debian 'dpkg' package management program version 1.18.26 (arm64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
```

**To Reproduce**
1. Fresh UDMp on 2.4.27
2. Attempt to install udm-boot
3. See the above
4. Cry?

**Expected behavior**
udm-boot getting installed

**UDM Information**
 - Variant: UDMp
 - Firmware Version: 2.4.27
 - Controller Version: Latest?

**Comment by boostchicken** [comment]
Try with the new udm-boot 1.0.6. make sure to re-download it

**Comment by cybik** [comment]
@boostchicken I actually tried both the github release and https://udm-boot.boostchicken.dev/; I ended up self-building instead with a small mod that forced gzip instead of zstd (https://stackoverflow.com/a/72359798).

No dice: `/sbin/ssh-proxy` is ***not present*** on the UDM(p) 2.4.27 release.

**Comment by boostchicken** [comment]
oh check out the remote_install.sh

**Comment by boostchicken** [comment]
try 1.0.7

**Comment by p-schneider** [comment]
[Version 1.0.7](https://github.com/unifi-utilities/unifios-utilities/raw/main/on-boot-script/packages/udm-boot_1.0.7_all.deb) resolves the Issue for me.
Thanks!

**Comment by cybik** [comment]
It installs, but it still fails:

```systemd[1]: /lib/systemd/system/udm-boot.service:10: Executable name contains special characters: mkdir -p /mnt/data/on_boot.d && find -L /mnt/data/on_boot.d -mindepth 1 -maxdepth 1 -type f -print0 | sort -z | xargs -0 -r -n 1 -- sh -c 'if test -x "$0"; then echo "udm-boot.service: running $0"; "$0"; else case "$0" in *.sh) echo "udm-boot.service: sourcing $0"; . "$0";; *) echo "udm-boot.service: ignoring $0";; esac; fi'```

**Comment by cybik** [comment]
Heavy-handed fix: replace the postinst line with the following.

```sed -i 's/\/sbin\/ssh-proxy/bash -c/' /lib/systemd/system/udm-boot.service```

**Comment by cybik** [comment]
That being said, the whole thing still uses `/mnt/data/on_boot.d` instead of `/data/on_boot.d`. Something to fix perhaps?
