### ISSUE TITLE
Instructions for setting up AdguardHome on Firmware versions 2+ is incorrect for location of 20-dns.conflist

### ISSUE THREAD

**Issue by adx9802** [unifi-utilities/unifios-utilities#480]
**Describe the bug**
[05-install-cni-plugins.sh](https://github.com/unifi-utilities/unifios-utilities/blob/main/cni-plugins/05-install-cni-plugins.sh) for firmware versions 2 and above look in /data
```
case "$(ubnt-device-info firmware || true)" in
    1*)
      DATA_DIR="/mnt/data"
      ;;
    2*)
      DATA_DIR="/data"
      ;;
    3*)
      DATA_DIR="/data"
      ;;
    *)
      echo "ERROR: No persistent storage found." 1>&2
      exit 1
      ;;
  esac
```

The instructions note that you have to copy 20-dns.conflist /mnt/data/podman/cni.  However for me to get 05-install-cni-plugins.sh to symbolically link the conflist in net.d correctly, I had to copy 20-dns.conflist to /data/podman/cni

**UDM Information**
 - Variant Dream Machine Pro
 - Firmware Version: [2.7.4]

**Comment by boostchicken** [comment]
Send a pull request!

**Comment by mhriemers** [comment]
I don't understand. The script is correct, no? For firmware versions from 2 and above, it copies to `/data/podman/cni`.

**Comment by adx9802** [comment]
ok will do and happy to in a bit!
