### ISSUE TITLE
[Feature Request] (att-ipv6) Allow for per-vlan DNS assignment

### ISSUE THREAD

**Issue by kb9gxk** [unifi-utilities/unifios-utilities#496]
@michaelw 
**Is your feature request related to a problem? Please describe.**
Currently the script allows for a single set of DNS to be assigned to the IPv6 VLAN

**Describe the solution you'd like**
Allow for the ability to assign each requested VLAN to have it's own DNS, or automatically point to ::1 for the VLAN

**Comment by michaelw** [comment]
@kb9gxk That should be possible by changing the dnsmasq configuration slightly: https://github.com/unifi-utilities/unifios-utilities/blob/main/att-ipv6/10-att-ipv6.sh#L86-L88

```sh
    var=dns6_$vv
    dhcp-option=tag:att-ipv6-${vv},option6:dns-server,${!var:-${dns6}}
```
Then you can set overrides at the beginning of the script:

```sh
dns6='<default DNS>'
dns6_br101='<dns for VLAN 101>'
dns6_br102='<dns for VLAN 102>'
```

Do you want to take a stab at a pull request for this?

**Comment by kb9gxk** [comment]
Thank you.  I made slight variations to that to allow for the Domain also, and moved the variables.

`  for vv in $vlans; do

    dnsvar=dns6_$vv
    domvar=domain_$vv
    cat <<EOF

interface=${vv}
dhcp-range=set:att-ipv6-${vv},::2,::7d1,constructor:${vv},slaac,ra-names,64,86400
dhcp-option=tag:att-ipv6-${vv},option6:dns-server,${!dnsvar:-${dns6}}
domain=${!domvar:-${domain}}|${vv}
ra-param=${vv},high,0
EOF
`

**Comment by boostchicken** [comment]
Thanks for following up and sharing your answer!
