### ISSUE TITLE
Support for UbiOS 2.5.x+

### ISSUE THREAD

**Issue by kb9gxk** [unifi-utilities/unifios-utilities#498]
Most scripts are starting with
`#!/bin/sh`

The newer systems are linking /bin/sh to /bin/dash

To fix the issue, scripts need to be adjusted to `#!/bin/bash` to work correctly.

**Comment by boostchicken** [comment]
sh is still on 2.5.x isnt it?  I just upgraded and installed podman on a UDM PRO, podman needs a little more process but udm-boot-2x 101 deb works great and does use bash

**Comment by boostchicken** [comment]
I just confirmed that /bin/sh is on  2.5.x  I am still happy to have it moved to bash or zsh as sh sucks,

**Comment by boostchicken** [comment]
https://github.com/unifi-utilities/unifios-utilities/pull/499

**Comment by boostchicken** [comment]
Please review the PR, once someone else reviews it ill merge

**Comment by kb9gxk** [comment]
> I just confirmed that /bin/sh is on 2.5.x I am still happy to have it moved to bash or zsh as sh sucks,

Yes /bin/sh is still on 2.5.x, but if you do a `ls -al /bin/sh`, you'll find that it points to /bin/dash

Thank you for agreeing to move it.  It will help so many people when the 2.5.x goes GA

**Comment by boostchicken** [comment]
Roger that thanks for clarification.  Go review my PR  and ill merge it
#499

**Comment by boostchicken** [comment]
Merged
