### ISSUE TITLE
Automatic Firmware Update from v1.12.38 to v2.4.27 wiped on-boot-script

### ISSUE THREAD

**Issue by mhubig** [unifi-utilities/unifios-utilities#503]
Some days ago I received automatic FW Updates from v1.12.38 to v2.4.27 on one UDM and one UDM Pro and on both systems the on-boot-scripts where completely wiped :-(

**Comment by TheWood1978** [comment]
Yeah as it said in the patch notes.

Note: Any 3rd party modifications made to the OS of the console will be lost after the upgrade, proceed with caution if you modified your console's OS.

Its deleted all data for on_boot.

It also seems to have removed unifi-os command too!

**Comment by boostchicken** [comment]
Yup, please look at the main brabch instructions updated
