### ISSUE TITLE
Cloudflared does not work

### ISSUE THREAD

**Issue by ddkedr** [unifi-utilities/unifios-utilities#518]
**Describe the bug**
Hello @peacey ! I'm a noob and I think I'll just ask a stupid question

I'm have my pihole running in host mode, which I've configured following [this](https://github.com/peacey/split-vpn/tree/main/pihole-host-mode) manual and it works fine.

Now I'm trying to run a cloudlared version of pihole from boostchicken following [this](https://github.com/unifi-utilities/unifios-utilities/tree/main/run-pihole#optional-builds) manual. So, all I did is modified `docker - run` command by changing docker image from `pihole/pihole:latest` to `boostchicken/pihole:latest` and adding two options: `-e CLOUDFLARED_OPTS="--port 5053 --address 0.0.0.0"` and `-e PIHOLE_DNS_="127.0.0.1#5053"` . And nothing else. Aaand it does not work :)

I feel that there also should be the Cloudflared installation process, but since I am a noob, I don't know how to do it.

Could you please guide me through the cloudflared installation process? I've thied to run [10-cloudflared.sh](https://github.com/unifi-utilities/unifios-utilities/blob/main/run-pihole/10-cloudflared.sh) script. But It says that port 127.0.0.1:53 is already busy.

Thanks a lot!

**Comment by boostchicken** [comment]
So I think this is a leftover.  Make sure cloudflared is chmod +x.  

Also do a "podman logs" on your container and post it here so we can see why its failing :)

**Comment by boostchicken** [comment]
Fixed in latest buld
