### ISSUE TITLE
nspawn-container - having network connection issues during initial setup - looking for confirmation

### ISSUE THREAD

**Issue by waffles0042** [unifi-utilities/unifios-utilities#544]
I updated my UDM-P to 3.20 earlier today and are now trying to get my PiHole installed on it again. I have been working my way through the [instructions](https://github.com/unifi-utilities/unifios-utilities/tree/main/nspawn-container), but keep running into network connection issues with the custom container.  
I wonder if I may have have run into a mix-up of the container vs. the gateway address: is what's shown for the Address for the file 'mv-br5.network' correct? See blue arrow. Shouldn't this /24 be part of the Gateway address, as shown in the other 2 screenshots? Thanks!

![image](https://user-images.githubusercontent.com/69690391/236362788-407e3e6e-bb5c-4074-870e-5823bd720959.png)
![image](https://user-images.githubusercontent.com/69690391/236362803-5c87f8b3-4da0-4c94-8a5f-45356ae9547c.png)
![image](https://user-images.githubusercontent.com/69690391/236362814-dd60a61d-230e-42de-a0a5-93757b37d340.png)

**Comment by waffles0042** [comment]
So I went with the installation as described above. While in the Debian Container, I can ping an IP address, but DNS does not seem to work. pinging google.com is not being recognized. Furthermore, my [pi-hole installation](https://github.com/unifi-utilities/unifios-utilities/blob/main/nspawn-container/examples/pihole/README.md) attempts fail:  


(sorry for the poor formatting...I tried to include the CLI content as code, but obviously failed :-( )
 
`Firmware version: v3.0.20

  ___ ___      .__________.__
 |   |   |____ |__\_  ____/__|
 |   |   /    \|  ||  __) |  |   (c) 2010-2023
 |   |  |   |  \  ||  \   |  |   Ubiquiti Inc.
 |______|___|  /__||__/   |__|
            |_/                  https://www.ui.com

      Welcome to UniFi Dream Machine Pro!

********************************* NOTICE **********************************
* By logging in to, accessing, or using any Ubiquiti product, you are     *
* signifying that you have read our Terms of Service (ToS) and End User   *
* License Agreement (EULA), understand their terms, and agree to be       *
* fully bound to them. The use of CLI (Command Line Interface) can        *
* potentially harm Ubiquiti devices and result in lost access to them and *
* their data. By proceeding, you acknowledge that the use of CLI to       *
* modify device(s) outside of their normal operational scope, or in any   *
* manner inconsistent with the ToS or EULA, will permanently and          *
* irrevocably void any applicable warranty.                               *
***************************************************************************
Last login: Thu May  4 21:44:49 2023 from 192.168.1.228
root@UDM-Pro:~# machinectl shell debian-custom
Connected to machine debian-custom. Press ^] three times within 1s to exit sessi                                                 on.
root@UDM-Pro:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=55 time=14.8 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=55 time=15.2 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=55 time=15.3 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=55 time=15.5 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=55 time=15.2 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=55 time=11.6 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=55 time=15.5 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=55 time=15.6 ms
^C
--- 1.1.1.1 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7009ms
rtt min/avg/max/mdev = 11.595/14.846/15.574/1.251 ms
root@UDM-Pro:~# apt -y install curl
curl -sSL https://install.pi-hole.net | PIHOLE_SKIP_OS_CHECK=true bash
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  ca-certificates libbrotli1 libcurl4 libldap-2.5-0 libldap-common
  libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1 openssl publicsuffix
Suggested packages:
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  ca-certificates curl libbrotli1 libcurl4 libldap-2.5-0 libldap-common
  libnghttp2-14 libpsl5 librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libssh2-1 openssl publicsuffix
0 upgraded, 15 newly installed, 0 to remove and 0 not upgraded.
Need to get 3290 kB of archives.
After this operation, 7769 kB of additional disk space will be used.
Ign:1 http://deb.debian.org/debian unstable/main arm64 openssl arm64 3.0.8-1
Ign:2 http://deb.debian.org/debian unstable/main arm64 ca-certificates all 20230                                                 311
Ign:3 http://deb.debian.org/debian unstable/main arm64 libbrotli1 arm64 1.0.9-2+                                                 b6
Ign:4 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules-db arm64                                                  2.1.28+dfsg-11
Ign:5 http://deb.debian.org/debian unstable/main arm64 libsasl2-2 arm64 2.1.28+d                                                 fsg-11
Ign:6 http://deb.debian.org/debian unstable/main arm64 libldap-2.5-0 arm64 2.5.1                                                 3+dfsg-5
Ign:7 http://deb.debian.org/debian unstable/main arm64 libnghttp2-14 arm64 1.52.                                                 0-1
Ign:8 http://deb.debian.org/debian unstable/main arm64 libpsl5 arm64 0.21.2-1
Ign:9 http://deb.debian.org/debian unstable/main arm64 librtmp1 arm64 2.4+201512                                                 23.gitfa8646d.1-2+b2
Ign:10 http://deb.debian.org/debian unstable/main arm64 libssh2-1 arm64 1.10.0-3                                                 +b1
Ign:11 http://deb.debian.org/debian unstable/main arm64 libcurl4 arm64 7.88.1-9
Ign:12 http://deb.debian.org/debian unstable/main arm64 curl arm64 7.88.1-9
Ign:13 http://deb.debian.org/debian unstable/main arm64 libldap-common all 2.5.1                                                 3+dfsg-5
Ign:14 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules arm64 2                                                 .1.28+dfsg-11
Ign:15 http://deb.debian.org/debian unstable/main arm64 publicsuffix all 2023020                                                 9.2326-1
Ign:1 http://deb.debian.org/debian unstable/main arm64 openssl arm64 3.0.8-1
Ign:2 http://deb.debian.org/debian unstable/main arm64 ca-certificates all 20230                                                 311
Ign:3 http://deb.debian.org/debian unstable/main arm64 libbrotli1 arm64 1.0.9-2+                                                 b6
Ign:4 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules-db arm64                                                  2.1.28+dfsg-11
Ign:5 http://deb.debian.org/debian unstable/main arm64 libsasl2-2 arm64 2.1.28+d                                                 fsg-11
Ign:6 http://deb.debian.org/debian unstable/main arm64 libldap-2.5-0 arm64 2.5.1                                                 3+dfsg-5
Ign:7 http://deb.debian.org/debian unstable/main arm64 libnghttp2-14 arm64 1.52.                                                 0-1
Ign:8 http://deb.debian.org/debian unstable/main arm64 libpsl5 arm64 0.21.2-1
Ign:9 http://deb.debian.org/debian unstable/main arm64 librtmp1 arm64 2.4+201512                                                 23.gitfa8646d.1-2+b2
Ign:10 http://deb.debian.org/debian unstable/main arm64 libssh2-1 arm64 1.10.0-3                                                 +b1
Ign:11 http://deb.debian.org/debian unstable/main arm64 libcurl4 arm64 7.88.1-9
Ign:12 http://deb.debian.org/debian unstable/main arm64 curl arm64 7.88.1-9
Ign:13 http://deb.debian.org/debian unstable/main arm64 libldap-common all 2.5.1                                                 3+dfsg-5
Ign:14 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules arm64 2                                                 .1.28+dfsg-11
Ign:15 http://deb.debian.org/debian unstable/main arm64 publicsuffix all 2023020                                                 9.2326-1
Ign:1 http://deb.debian.org/debian unstable/main arm64 openssl arm64 3.0.8-1
Ign:2 http://deb.debian.org/debian unstable/main arm64 ca-certificates all 20230                                                 311
Ign:3 http://deb.debian.org/debian unstable/main arm64 libbrotli1 arm64 1.0.9-2+                                                 b6
Ign:4 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules-db arm64                                                  2.1.28+dfsg-11
Ign:5 http://deb.debian.org/debian unstable/main arm64 libsasl2-2 arm64 2.1.28+d                                                 fsg-11
Ign:6 http://deb.debian.org/debian unstable/main arm64 libldap-2.5-0 arm64 2.5.1                                                 3+dfsg-5
Ign:7 http://deb.debian.org/debian unstable/main arm64 libnghttp2-14 arm64 1.52.                                                 0-1
Ign:8 http://deb.debian.org/debian unstable/main arm64 libpsl5 arm64 0.21.2-1
Ign:9 http://deb.debian.org/debian unstable/main arm64 librtmp1 arm64 2.4+201512                                                 23.gitfa8646d.1-2+b2
Ign:10 http://deb.debian.org/debian unstable/main arm64 libssh2-1 arm64 1.10.0-3                                                 +b1
Ign:11 http://deb.debian.org/debian unstable/main arm64 libcurl4 arm64 7.88.1-9
Ign:12 http://deb.debian.org/debian unstable/main arm64 curl arm64 7.88.1-9
Ign:13 http://deb.debian.org/debian unstable/main arm64 libldap-common all 2.5.1                                                 3+dfsg-5
Ign:14 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules arm64 2                                                 .1.28+dfsg-11
Ign:15 http://deb.debian.org/debian unstable/main arm64 publicsuffix all 2023020                                                 9.2326-1
Err:1 http://deb.debian.org/debian unstable/main arm64 openssl arm64 3.0.8-1
  Temporary failure resolving 'deb.debian.org'
Err:2 http://deb.debian.org/debian unstable/main arm64 ca-certificates all 20230                                                 311
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian unstable/main arm64 libbrotli1 arm64 1.0.9-2+                                                 b6
  Temporary failure resolving 'deb.debian.org'
Err:4 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules-db arm64                                                  2.1.28+dfsg-11
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian unstable/main arm64 libsasl2-2 arm64 2.1.28+d                                                 fsg-11
  Temporary failure resolving 'deb.debian.org'
Err:6 http://deb.debian.org/debian unstable/main arm64 libldap-2.5-0 arm64 2.5.1                                                 3+dfsg-5
  Temporary failure resolving 'deb.debian.org'
Err:7 http://deb.debian.org/debian unstable/main arm64 libnghttp2-14 arm64 1.52.                                                 0-1
  Temporary failure resolving 'deb.debian.org'
Err:8 http://deb.debian.org/debian unstable/main arm64 libpsl5 arm64 0.21.2-1
  Temporary failure resolving 'deb.debian.org'
Err:9 http://deb.debian.org/debian unstable/main arm64 librtmp1 arm64 2.4+201512                                                 23.gitfa8646d.1-2+b2
  Temporary failure resolving 'deb.debian.org'
Err:10 http://deb.debian.org/debian unstable/main arm64 libssh2-1 arm64 1.10.0-3                                                 +b1
  Temporary failure resolving 'deb.debian.org'
Err:11 http://deb.debian.org/debian unstable/main arm64 libcurl4 arm64 7.88.1-9
  Temporary failure resolving 'deb.debian.org'
Err:12 http://deb.debian.org/debian unstable/main arm64 curl arm64 7.88.1-9
  Temporary failure resolving 'deb.debian.org'
Err:13 http://deb.debian.org/debian unstable/main arm64 libldap-common all 2.5.1                                                 3+dfsg-5
  Temporary failure resolving 'deb.debian.org'
Err:14 http://deb.debian.org/debian unstable/main arm64 libsasl2-modules arm64 2                                                 .1.28+dfsg-11
  Temporary failure resolving 'deb.debian.org'
Err:15 http://deb.debian.org/debian unstable/main arm64 publicsuffix all 2023020                                                 9.2326-1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openssl/openssl_3.0.                                                 8-1_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/ca-certificates/ca-c                                                 ertificates_20230311_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/b/brotli/libbrotli1_1.                                                 0.9-2%2bb6_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2                                                 -modules-db_2.1.28%2bdfsg-11_arm64.deb  Temporary failure resolving 'deb.debian.                                                 org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2                                                 -2_2.1.28%2bdfsg-11_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openldap/libldap-2.5                                                 -0_2.5.13%2bdfsg-5_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/nghttp2/libnghttp2-1                                                 4_1.52.0-1_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libp/libpsl/libpsl5_0.                                                 21.2-1_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/r/rtmpdump/librtmp1_2.                                                 4%2b20151223.gitfa8646d.1-2%2bb2_arm64.deb  Temporary failure resolving 'deb.deb                                                 ian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/libs/libssh2/libssh2-1                                                 _1.10.0-3%2bb1_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/curl/libcurl4_7.88.1                                                 -9_arm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/curl/curl_7.88.1-9_a                                                 rm64.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/o/openldap/libldap-com                                                 mon_2.5.13%2bdfsg-5_all.deb  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/c/cyrus-sasl2/libsasl2                                                 -modules_2.1.28%2bdfsg-11_arm64.deb  Temporary failure resolving 'deb.debian.org                                                 '
E: Failed to fetch http://deb.debian.org/debian/pool/main/p/publicsuffix/publics                                                 uffix_20230209.2326-1_all.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-mis                                                 sing?
bash: curl: command not found
root@UDM-Pro:~# ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=55 time=15.4 ms
64 bytes from 1.1.1.1: icmp_seq=2 ttl=55 time=14.0 ms
64 bytes from 1.1.1.1: icmp_seq=3 ttl=55 time=14.9 ms
64 bytes from 1.1.1.1: icmp_seq=4 ttl=55 time=15.1 ms
64 bytes from 1.1.1.1: icmp_seq=5 ttl=55 time=14.3 ms
64 bytes from 1.1.1.1: icmp_seq=6 ttl=55 time=15.6 ms
64 bytes from 1.1.1.1: icmp_seq=7 ttl=55 time=14.9 ms
64 bytes from 1.1.1.1: icmp_seq=8 ttl=55 time=15.9 ms
^C
--- 1.1.1.1 ping statistics ---
8 packets transmitted, 8 received, 0% packet loss, time 7008ms
rtt min/avg/max/mdev = 14.032/15.010/15.869/0.582 ms
root@UDM-Pro:~# ping google.com
ping: google.com: Temporary failure in name resolution
root@UDM-Pro:~# update-alternatives --set iptables /usr/sbin/iptables-legacy
update-alternatives: error: no alternatives for iptables
`

Any help would be greatly appreciated!

**Comment by waffles0042** [comment]
Here is what I get for 
ip addr show

![image](https://user-images.githubusercontent.com/69690391/236571638-e2537e0d-d2a7-4ed6-be45-cf4202dc1547.png)

**Comment by waffles0042** [comment]
I think I got it working now.

1. the IP configurations in the guide are correct  (=> my initial post)
 
2. I think I had missed this step (even though I had used the scripted install)
![image](https://user-images.githubusercontent.com/69690391/236644413-5c939222-9359-4ae3-bbdb-363c65c62b46.png)

Once I manually added "nameserver 1.1.1.1"
![image](https://user-images.githubusercontent.com/69690391/236644446-e1d8cfa4-61ba-4588-ab72-714b30453f23.png)

.... I was able to complete the PiHole installation. 

All set for now!

Hope this is helpful to s.o. in a similar situation.

**Comment by NullVoxPopuli** [comment]
if you're using `1.1.1.1` for the sameserver, does that mean you're not use the pi-hole for DNS?

**Comment by waffles0042** [comment]
> if you're using `1.1.1.1` for the nameserver, does that mean you're not use the pi-hole for DNS?

I am
![image](https://github.com/unifi-utilities/unifios-utilities/assets/69690391/d0d593aa-4a6a-49f8-b7e1-533e1a5ed929)

But to be able to install PiHole in the first place, I needed an 'outside' name server, as far as I understand.
