### ISSUE TITLE
att-ipv6 stops working with UDM Pro 3.0.20

### ISSUE THREAD

**Issue by mweberjc** [unifi-utilities/unifios-utilities#549]
With the latest upgrades podman stops works (#521).  Running dhcpcd manually (in a chroot) does not seem to fix this entirely, as there are no router advertisements being sent anymore (presumably because we turned off IPv6 to take it over.  

EDIT: the dnsmasq configuration got clobbered.  As long as dhcpcd is started successfully in other ways than with podman, things will still work as before.

**Comment by keith8496** [comment]
@mweberjc, can you elaborate on how you got it to work 3.0.20? 

I almost have it working under a nspawn container except something is intermittently removing the ipv6 config from the wan interface. My best guess is that a native process on the udmp is competing with dhcpcd in the container.
