### ISSUE TITLE
unifi.boostchicken.io down?

### ISSUE THREAD

**Issue by bilke** [unifi-utilities/unifios-utilities#565]
**Describe the bug**

I am trying to install podman (https://github.com/unifi-utilities/unifios-utilities/tree/main/podman-install) and when I am running the install script [00-podman.sh](https://github.com/unifi-utilities/unifios-utilities/blob/main/podman-install/on_boot.d/00-podman.sh) it fails with

```
downloading https://unifi.boostchicken.io/udmpro-podman-install.zip
download failed
```

**To Reproduce**

1. Open https://unifi.boostchicken.io in your browser
2. Error: `failed to resolve /ipns/unifi.boostchicken.io/: could not resolve name`

**UDM Information**
 - Variant: UDM
 - Firmware Version: v3.1.15
 - Controller Version: 7.4.162

**Comment by SamErde** [comment]
I believe Podman no longer runs on the 3.x firmware. Please see the following issues: 
 - #543  
 - #537  
 - #523  
 - #428

**Comment by ausfestivus** [comment]
What if it's related to any CloudFlare shenanigans?

https://www.cloudflarestatus.com/
![Screenshot 2023-08-30 at 11 39 36 am](https://github.com/unifi-utilities/unifios-utilities/assets/40222285/3b814787-f59e-4310-ae63-4729bfc54e35)
![Screenshot 2023-08-30 at 11 40 23 am](https://github.com/unifi-utilities/unifios-utilities/assets/40222285/eadafbeb-829e-4410-a72b-57368aaaffd3)

**Comment by ausfestivus** [comment]
Tagging @boostchicken on this since he hasnt been already and its his service I believe.

**Comment by CaptInsano** [comment]
Came here to ask about this too.

podman install failing here too due to boostchicken.io being down.

@boostchicken any update on a fix or mirror for the files?

Thanks so much.

**Comment by basher83** [comment]
Still down for me :(

**Comment by boostchicken** [comment]
It should be its a cloudflare gateway

**Comment by CaptInsano** [comment]
> It should be its a cloudflare gateway

It should be up? It is defo not up here anyway.

Output from wget to test it:

```
# wget https://unifi.boostchicken.io/udmpro-podman-install.zip
--2023-09-13 08:32:35--  https://unifi.boostchicken.io/udmpro-podman-install.zip
Resolving unifi.boostchicken.io (unifi.boostchicken.io)... 172.66.41.11, 172.66.42.245, 2606:4700:3108::ac42:290b, ...
Connecting to unifi.boostchicken.io (unifi.boostchicken.io)|172.66.41.11|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-09-13 08:32:53 ERROR 500: Internal Server Error.
```

Any other advice on making it work from the user end?

Thanks a million

**Comment by basher83** [comment]
> cloudflare gateway

I get the following:

failed to resolve /ipns/unifi.boostchicken.io/: could not resolve name

**Comment by m4n63** [comment]
Sidenote, does podman actually work on recent versions of UDM? 

I thought you needed to use another approach to run containers where this package is not needed.

**Comment by Aura-Bella-Fiora** [comment]
Down for me too:

 wget https://unifi.boostchicken.io/udmpro-podman-install.zip
--2023-09-15 17:51:04--  https://unifi.boostchicken.io/udmpro-podman-install.zip
Resolving unifi.boostchicken.io (unifi.boostchicken.io)... 172.66.41.11, 172.66.42.245, 2606:4700:3108::ac42:290b, ...
Connecting to unifi.boostchicken.io (unifi.boostchicken.io)|172.66.41.11|:443... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2023-09-15 17:51:23 ERROR 500: Internal Server Error.

**Comment by kalebmmm** [comment]
Down for me as well

**Comment by austin-millan** [comment]
Still down for ~1mo.

**Comment by austin-millan** [comment]
This seems to be a workaround: https://github.com/unifi-utilities/unifios-utilities/issues/533#issuecomment-1510594817

I'd say do this at your own risk, though. Seems like it's just an old backup stored on someone's Nextcloud instance. I am not familiar with this host or why other people here have been deciding to use it. There's no way to easily validate the authenticity of the files or if they are malicious. But the binary stored on that server supposedly comes with podman 3.4.4. I guess the question is who wants podman bad enough? 

Maybe we should mirror these artifacts elsewhere.

**Comment by emcniece** [comment]
Still down :(

**Comment by Rexus** [comment]
Any hopes for this ? Still down and from the looks of this it has been a while.

**Comment by rchad86** [comment]
*bump* still ded

**Comment by rwgnr** [comment]
@boostchicken help :(

**Comment by rootelement** [comment]
@boostchicken help!

**Comment by boostchicken** [comment]
My server is toast.  My new stuf just go herem building a whole need rig.
Do you need something in the mean time.  I can see if I can rip it off some
backuops

**Comment by rootelement** [comment]
Can you attach the podman zip to this comment thread that you had hosted so we can at least download it in the interim? Or point us to the source that's in it? Whatever will allow us to get through this?
https://github.com/unifi-utilities/unifios-utilities/tree/main/podman-install

**Comment by boostchicken** [comment]
WE are alive!

**Comment by benjaminprojas** [comment]
> https://unifi.boostchicken.io/udmpro-podman-install.zip

Still getting this original error as of today. When I visit the URL it does not exist, though other files do exist at unifi.boostchicken.io.

**Comment by benjaminprojas** [comment]
> Should be back. I replaced my entire network

This is what I am seeing: 
![image](https://github.com/unifi-utilities/unifios-utilities/assets/962530/fb8968c3-030a-449d-bea7-d41f2a5084b3)

**Comment by RlndVt** [comment]
Next to the `failed to resolve /ipns/unifi.boostchicken.io/udmpro-podman-install.zip: no link named "udmpro-podman-install.zip" under QmZgpm58fKx9qcdZ5CKymT1ABsZXQCsK8efobK7kyExqsb
`  on https://unifi.boostchicken.io/udmpro-podman-install.zip, we(/I) see the following on https://unifi.boostchicken.io/


![image](https://github.com/unifi-utilities/unifios-utilities/assets/1658570/7165f1d3-3edd-4c8e-851c-3ac1eea5f25a)

What is the zip we should grab?

**Comment by boostchicken** [comment]
Id get thet latest zip for your hardware

**Comment by RlndVt** [comment]
Thanks!

The code doesn't seem to line-up with the files listed. That is; accoring to the website file list, UDM has a unique zip file, while UDM-PRO and UDM-SE share a file. Comparing that to the code:

```
case "$(udm_model)" in
udmse | udmpro)
  DESIRED_ZIPFILE="$(udm_model)-podman-install.zip"
  ;;
udm)
  # base UDM works fine with udmpro podman version, but has issues with udmse variant
  DESIRED_ZIPFILE="udmpro-podman-install.zip"
  DESIRED_ZIPFILE="udmpro-podman-install.zip"
  ;;
*)
  # shrug
  # udmse-podman-install.zip seems to work fine on UDM 2.4.x
  true
  ;;
esac
```

UDM-SE and UDM-Pro should use their unique podman build, while UDM should 'fallback' to the UDM-Pro version. Shall I make a seperate issue for this?

**Comment by dvcrn** [comment]
IPFS host is dead for me again. Any mirror?

**Comment by boostchicken** [comment]
That server has died for the last time I'm over it let me see if I can a
mirror

**Comment by arjundhanjal** [comment]
Hey @boostchicken -- looks like your site is still down. Are you able to provide the files or a mirror for podman-install?

**Comment by dvcrn** [comment]
@boostchicken maybe consider using a pinning service like pinata, or upload into github releases for hosting

**Comment by boostchicken** [comment]
I pin them both locally and on pinata, let me check the account and see why
its not functionin2g.

**Comment by dvcrn** [comment]
Maybe instead of your custom domain, we could try a couple of ipfs gateways as backup? Can you post the IPFS hash here? 

But yeah it looks like ipns doesn't resolve to anything for it

**Comment by dokicro** [comment]
> This seems to be a workaround: [#533 (comment)](https://github.com/unifi-utilities/unifios-utilities/issues/533#issuecomment-1510594817)
> 
> I'd say do this at your own risk, though. Seems like it's just an old backup stored on someone's Nextcloud instance. I am not familiar with this host or why other people here have been deciding to use it. There's no way to easily validate the authenticity of the files or if they are malicious. But the binary stored on that server supposedly comes with podman 3.4.4. I guess the question is who wants podman bad enough?
> 
> Maybe we should mirror these artifacts elsewhere.

I am not sure why everybody is ignoring this and [#533 (comment)](https://github.com/unifi-utilities/unifios-utilities/issues/533#issuecomment-1510594817) this solves your issue!

**Comment by dvcrn** [comment]
> I am not sure why everybody is ignoring this and #533 (comment) this solves your issue!

Because it puts the trust into a random other server. You're installing a binary that could include whoknowswhat 

(Not saying the current ipfs hosted one is better, but still)

**Comment by boostchicken** [comment]
She is back!

**Comment by dvcrn** [comment]
I went ahead and pinned `QmZgpm58fKx9qcdZ5CKymT1ABsZXQCsK8efobK7kyExqsb` on my pinata.cloud instance and local IPFS node. Hope that helps with keeping the share alive

**Comment by boostchicken** [comment]
Thanks so much! I recovered most of my raidz1 zfs drive but lost my ipfs server, luckily I had a up to date back up in Pinata which is where it is now. 

You can probably remove your Pinata pin no need for two on the same infra. Your call, doesn't hurt anything.

My ipns dns links are hard coded to my cids via cloud flare, If you give me permission I'll make sure it round robins between me and you.

**Comment by dvcrn** [comment]
I think it shouldn't matter, the more nodes (local, hosted, etc) have the cid pinned, the more distributed it is, and the the easier it is for the network to retrieve it again. So me pinning them will make your cloudflare ipfs gateway also quicker in retrieving it 👍 

Pinata isn't very fast, best would be to have an actual server somewhere pinning it, but then it may just be better to self-host and not use IPFS haha. But if you have a VPS idling around somewhere, pinning the cid on that one would probably have the best effects

**Comment by boostchicken** [comment]
> I think it shouldn't matter, the more nodes (local, hosted, etc) have the cid pinned, the more distributed it is, and the the easier it is for the network to retrieve it again. So me pinning them will make your cloudflare ipfs gateway also quicker in retrieving it 👍 
> 
> Pinata isn't very fast, best would be to have an actual server somewhere pinning it, but then it may just be better to self-host and not use IPFS haha. But if you have a VPS idling around somewhere, pinning the cid on that one would probably have the best effects

Thanks for the education I am still an ipfs noob, I'll be putting it on my server with redundant 1gig internet.

Is there any way to pin it locally from Pinata?

**Comment by dvcrn** [comment]
Here's a crashcourse:

- You put the file on your own IPFS node (or pinata or wherever), and you get a CID for it 
- If someone wants to download the file, the IPFS network will search and connect over different peers until it finds peers that have the file with this CID 
- If no node has the CID anymore, the data is considered deleted off the IPFS network 

If you type "[bafybeifitoeyohlgttrcivq6xwfkobueoncwyrdig44izro7q2bhfdkply.ipfs.cf-ipfs.com](https://bafybeifitoeyohlgttrcivq6xwfkobueoncwyrdig44izro7q2bhfdkply.ipfs.cf-ipfs.com/)", the CloudFlare IPFS node is looking through the IPFS network to find `bafybeifitoeyohlgttrcivq6xwfkobueoncwyrdig44izro7q2bhfdkply`, then downloads it from the peers that have it, and caches it locally to make it accessible faster. If you have IPFS running locally, and only you have the file, then CloudFlare will download it from your IPFS node. 

If you "pin" a CID on an IPFS node, be it local, Pinata, your server, or somewhere else, the IPFS node downloads the file to its local storage and starts advertising it, effectively increasing the number of nodes that own the CID. 

So if my local machine pins it, my pinata pins it, your pinata pins it and your server pins it, we'll have a lot more nodes available that replicate the data, effectively making it more available. 

(Personal take: out of the options provided, running an IPFS node on your server as an additional pin seems like the best option. It likely has the best upload/download rate. Pinata is quite slow)
