### ISSUE TITLE
Update att-ipv6 for 3.x (and dream router)

### ISSUE THREAD

**Issue by stcbus** [unifi-utilities/unifios-utilities#577]
I got the UDR with 3.x which apparently doesn't do containers anymore. Could the att-ipv6 stuff be updated to work in 3.x?

**Comment by boostchicken** [comment]
yeah i do it just fine on 3.  Let me know if you still need help

**Comment by stcbus** [comment]
Definitely would appreciate a guide or some tips on that. I am familiar
with running scripts just not sure what would change. Thanks!

**Comment by boostchicken** [comment]
so the att-ipv6 stuff isnt needed if you bypass their RG. Are you doing that, EAP Proxy? or certs with WPA?

**Comment by stcbus** [comment]
I am not, but maybe can investigate that again. I didn't think I had the
right RG setup for it when I last looked.

**Comment by boostchicken** [comment]
you can buy certs on ebay i believe.  Iff you have tge BGW320, there is no bypass as far as I know
