### ISSUE TITLE
Project discontinued?

### ISSUE THREAD

**Issue by EugenMayer** [unifi-utilities/unifios-utilities#597]
Thank you for your hard work!

Seems like there is not a lot of movement any longer, esp toward UnifiOS 3.x (which has been released more then 1 year ago).

Should this project be considered archived/frozen/discontinued

**Comment by dhergert** [comment]
Per the README on https://github.com/unifi-utilities/unifios-utilities provides instructions on getting it working in UnifiOS 3.x.

> ⚠️ Breaking Changes for UniFi OS 3.x
> UniFi OS 3.x no longer supports podman. The utilities in this respository may not work as documented. For alternatives, review the documentation in nspawn-container (https://github.com/unifi-utilities/unifios-utilities/tree/main/nspawn-container)...

**Comment by EugenMayer** [comment]
I was not asking how to get 3.x up and working, this was up and running for me long before i opened this issue. It was not a ask for help, but rather a question of state.

Looking at the repository, it kind of speak for itself, a lot of the details are not (no longer) working, not to speak of the overcomplication of installation since it has all stopped in an "early stage". It just seems things have been abondened, maybe because Unifi moved to nspwan and classic docker based extensions are no longer working / extra effort is required. 

Maybe people just moved to a different project or simply moved on to other projects - nothing of shame, fair enough. A great deal of work has been done in the past and one can be greatfull.

But knowing what the plans are or at least, if there are none, is still of value

**Comment by Silvenga** [comment]
I'm going to say yes: https://www.reddit.com/r/Ubiquiti/comments/199ketk/moving_to_mikrotik_for_coretransit_its_been_real/kieqduy/

**Comment by EugenMayer** [comment]
@Silvenga how is that reddit post related to the project own / contributors (sorry, not able to link those).

**Comment by Silvenga** [comment]
@EugenMayer At least from my perspective (from the comment I linked):

- The owner of this repository (Boostchicekn) has moved away from Ubiquiti products. He has sold his Ubiquiti gear - meaning, without a transfer of ownership to the community, there's not much that can be done (unless someone else has gotten admin permissions that I don't know about, he's the only member listed in the [GH org](https://github.com/unifi-utilities)). Testing on actual hardware by the owner of this repository is unlikely to happen.
- As he mentions, someone was threatening him over his work on this repository (open source code that is without warranty). He mentions other stories as such.

So without a fork from the community, it might be best to consider this project sunset as the core maintainer appears completely burntout (and I can't blame him, assuming his stories are correct).

**Comment by EugenMayer** [comment]
@Silvenga i'am considering opening my (yet) private repository with 3.x work for backups/rclone/adguard for the public, but i would love to hear about those threats.

What threats, that something did go south during a script and someone wanted to make this a case of 'warrant' against boostchicken?

**Comment by m4n63** [comment]
I agree, there is too much old stuff here not working with the recent hardware/software. It would be good to open a new repo and just copy over any repo that someone is willing to maintain going forward.

**Comment by Silvenga** [comment]
@EugenMayer that's only for boostchicken to delve into - I only know what he's hinted publicly. 

TBH, it's unfortunately not uncommon. I've had iffy people go after me personally for my OSS work in the past. Outside of bad people being bad, OSS work is largely unthankless and burnout is real.

**Comment by EugenMayer** [comment]
Thank your for sharing your insight! 

I'am not exactly new to OSS but that is a different topic, so i would not exactly share your opinion, but depending on the env, it can be very hostile at points. But let's keep this thread on-topic.

I will keep this issue open for others to read / participate. 

Should i make my current udm efforts public i would port a link here, but i did yet not make up my mind if and under which boundaries i would release it.

**Comment by boostchicken** [comment]
I don't think a fork or re-host is prudent, if anyone is interested in becoming a maintainer please let me know, I no longer use unifi gateways so I can't test

**Comment by EugenMayer** [comment]
At least talking for myself, i'am not going to opt in as a maintainer of this repository, beside i really value the actual work that has been done here.

Things like:
 
- homebridge
- haproxy
  
and a couple more are just no longer things i consider part of an UDM/Gateway. I understand that people have different needs, and most of the apps i run myself anyway - just on different platforms (where those belong), be it k8s, baremetal or appliances. Coming from OPNsense, which goes down a similar (like this repo) path right now, i will not invest time in helping people run "anything"  on gateways/routers (for whatever reasons there is). Security wise, this is a disaster in itself.

This said, i might still contribute to the project (if it is helpful and accepted) in the areas i see sane, but not as an maintainer of it all.

**Comment by boostchicken** [comment]
> I was not asking how to get 3.x up and working, this was up and running for me long before i opened this issue. It was not a ask for help, but rather a question of state.
> 
> Looking at the repository, it kind of speak for itself, a lot of the details are not (no longer) working, not to speak of the overcomplication of installation since it has all stopped in an "early stage". It just seems things have been abondened, maybe because Unifi moved to nspwan and classic docker based extensions are no longer working / extra effort is required. 
> 
> Maybe people just moved to a different project or simply moved on to other projects - nothing of shame, fair enough. A great deal of work has been done in the past and one can be greatfull.
> 
> But knowing what the plans are or at least, if there are none, is still of value

What is happening is the Ubi finally added all the features so the need for this is way for if not non existent.

I have written the vast majority of everything you see here, I can't test changes or new stuff unless someone wants to drop me on their device. I still have a UDMP sitting around but it doesn't play nice if I put it on the network. Wish we got virtualization working.

I will try to put it on the network again but in an isolated vlan this time maybe that will solve my issues

By the way, the project only dies if you guys let it. I'll add anyone a maintainer to the repo just ask.

**Comment by boostchicken** [comment]
Also regarding the harassment, absolutely real. Putting containers on the UDM is taboo and my scripts cause such a massive support burden to Ubi that I should take it down. Ask me for that discord log it fun. Since I am hurting U bi some people felt compelled to try and hurt me.

I should have just ignored these haters but instead I had to make them look stupid which was my mistake and something I regret. I got on their level for a bit sadly 

Can someone explain to my why networking experts are so angry?

**Comment by boostchicken** [comment]
> I agree, there is too much old stuff here not working with the recent hardware/software. It would be good to open a new project and just copy over any repo that someone is willing to maintain going forward.

Make  a branch and clean it up and then send a PR I'll merge.

**Comment by boostchicken** [comment]
So this seeing you guys come together in a mature fashion and communicating effectively and empathizing with some of my struggles related to OSS has rejuvenated my desire to keep this project going.

It's not discontinued, and to prove my commitment to it I have gone ahead and made some long over due bugfixes and merged some other bug fixes from some forks.

I challenge you all to send PRs as well. There are some issues that were so detailed that it literally was a copy paste fix and then a merge. If you put in that effort get the credit! There are a lot of benefits to have OSS contributions on your resume as well especially in high traffic repo like this (thousands of unique visitors as day at it's peak, now more like 1.2k with tons of linkbacks)

Thanks everyone for being understanding.

**Comment by EugenMayer** [comment]
Assuming the issue above has been solved in some manner (even though i assume the project has been fallen asleep again, IMHO). Nevertheless, i close the issue
