### ISSUE TITLE
Documentation: Please update curl commands in nspawn-container article

### ISSUE THREAD

**Issue by lwbt** [unifi-utilities/unifios-utilities#601]
**Describe the bug**
Please update curl commands in nspawn-container article, after reading it once more and comparing the scripts I found a few differences because the other repo is a few commits behind.

**To Reproduce**
1. Go to https://github.com/unifi-utilities/unifios-utilities/tree/main/nspawn-container
2. Check "Step 2A: Configure the Container to use an Isolated MacVLAN Network" and compare links in text and code block
3. Scroll down to "Step 3: Configure Persistence Across Firmware Updates" and compare links in text and code block
4. A repository `peacey/unifios-utilities` is used instead of `unifi-utilities/unifios-utilities`

**Expected behavior**
- The links should be the same.
- No content outside this repo should be fetched with curl without telling the reader about it.

**Additional context**
- It could be a potential security issue in the future, but that's a bit far fetched, lets just say things should work as they are intended to be.

```diff
-curl -LO https://raw.githubusercontent.com/peacey/unifios-utilities/nspawn/nspawn-container/scripts/10-setup-network.sh
+curl -LO https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/nspawn/nspawn-container/scripts/10-setup-network.sh
```

```diff
-curl -LO https://raw.githubusercontent.com/peacey/unifios-utilities/nspawn/nspawn-container/scripts/0-setup-system.sh
+curl -LO https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/nspawn/nspawn-container/scripts/0-setup-system.sh
```

**Comment by boostchicken** [comment]
Send a PR plz

**Comment by boostchicken** [comment]
I fixed it because of security issues
