### ISSUE TITLE
[BUG] ERROR: No persistent storage found.

### ISSUE THREAD

**Issue by bslatyer** [unifi-utilities/unifios-utilities#602]
**Describe the bug**
Attempting to install the 2.x on_boot script via cURL results in the following error
`ERROR: No persistent storage found.`

**To Reproduce**
1. Access the UDM-SE via SSH
2. Run the following script `curl -fsL "https://raw.githubusercontent.com/unifi-utilities/unifios-utilities/HEAD/on-boot-script-2.x/remote_install.sh" | /bin/sh`
3. Results in the above error

**Expected behavior**
The script is meant to run without errors.

**UDM Information**
 - Device: `UniFi Dream Machine SE (UDM-SE)`
 - Firmware Version: `UniFi OS 4.0.3 (EA)`
 - Controller Version: `8.1.127 (EA)`

**Additional context**
Manually installing the `udm-boot-2x_1.0.1_all.deb` via SSH works as expected

**Comment by shirt-dev** [comment]
I believe https://github.com/unifi-utilities/unifios-utilities/blob/main/cni-plugins/05-install-cni-plugins.sh needs to be updated as well

**Comment by boostchicken** [comment]
> I believe https://github.com/unifi-utilities/unifios-utilities/blob/main/cni-plugins/05-install-cni-plugins.sh needs to be updated as well

Done
